# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('credit_type', models.IntegerField(choices=[(0, '竞赛获奖'), (1, '学术论文'), (2, '国家发明专利'), (3, '大学生创新项目')], verbose_name='认定类型')),
                ('value', models.IntegerField(verbose_name='认定学分')),
                ('name', models.CharField(max_length=300, verbose_name='名称')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('grade', models.IntegerField()),
                ('major', models.IntegerField(choices=[(0, '暂无'), (1, '软件技术与管理'), (2, '网络与主机软件'), (3, '嵌入式软件与系统'), (4, '数字媒体'), (5, '其他')], default=0)),
                ('phone', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
