# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='image',
            field=models.ImageField(null=True, upload_to='img', verbose_name='认证图片'),
        ),
    ]
