# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('credit_type', models.IntegerField(choices=[(0, '竞赛获奖'), (1, '学术论文'), (2, '国家发明专利'), (3, '大学生创新项目')], verbose_name='认定类型')),
                ('value', models.IntegerField(verbose_name='认定学分')),
                ('name', models.CharField(max_length=300, verbose_name='名称')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
