# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='schoolid',
        ),
    ]
