# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160406_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
