# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160406_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_third_type',
            field=models.IntegerField(choices=[(11, '一等奖'), (12, '二等奖'), (13, '三等奖'), (21, '第一作者'), (22, '第二作者'), (23, '第三作者'), (0, '无')], default='13', verbose_name='认定等级3'),
        ),
        migrations.AddField(
            model_name='credit',
            name='grade',
            field=models.IntegerField(choices=[(5, '优'), (4, '良'), (3, '中'), (2, '及格'), (0, '暂无')], default=0, verbose_name='学分等级'),
        ),
        migrations.AddField(
            model_name='credit',
            name='status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '未通过'), (2, '已通过')], default=0, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_type',
            field=models.IntegerField(choices=[(1, '竞赛获奖'), (2, '学术论文'), (3, '国家发明专利'), (4, '大学生创新项目')], default='1', verbose_name='认定类型'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='value',
            field=models.IntegerField(default=0, verbose_name='认定学分'),
        ),
    ]
