# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160407_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit_type',
            field=models.IntegerField(choices=[(1, '竞赛获奖'), (2, '学术论文'), (3, '国家发明专利'), (4, '大学生创新项目')], verbose_name='认定类型'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='value',
            field=models.IntegerField(default=0, verbose_name='认定学分'),
        ),
    ]
