# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160408_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['create_credit_date']},
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='date',
            new_name='create_credit_date',
        ),
        migrations.AddField(
            model_name='credit',
            name='get_project_date',
            field=models.DateTimeField(null=True),
        ),
    ]
