# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160409_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='create_credit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='get_project_date',
            field=models.DateField(null=True),
        ),
    ]
