# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160409_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='credit_second_type',
            field=models.IntegerField(choices=[(11, '校级'), (12, '省级'), (13, '国家级'), (14, '国际级'), (15, '其他'), (21, '权威报纸'), (22, '核心期刊'), (23, 'SCI/EI检索'), (0, '无')], default='11', verbose_name='认定等级2'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_third_type',
            field=models.IntegerField(choices=[(11, '一等奖'), (12, '二等奖'), (13, '三等奖'), (21, '第一作者'), (22, '第二作者'), (23, '第三作者'), (0, '无')], default='11', verbose_name='认定等级3'),
        ),
    ]
